gazebo:
  delay: 0.009
  imus:
    base_imu:
      frame_id: base_imu
      orientation_covariance_diagonal: [ 0.0012, 0.0012, 0.0012 ]
      angular_velocity_covariance: [ 0.0004, 0.0004, 0.0004 ]
      linear_acceleration_covariance: [ 0.01, 0.01, 0.01 ]
  contacts: [ "LF_FOOT", "LH_FOOT", "RF_FOOT", "RH_FOOT" ]
  /gazebo_ros_control:
    pid_gains:
      LF_foot:
        p: 100.0
        i: 0.01
        d: 10.0
      LH_foot:
        p: 100.0
        i: 0.01
        d: 10.0
      RF_foot:
        p: 100.0
        i: 0.01
        d: 10.0
      RH_foot:
        p: 100.0
        i: 0.01
        d: 10.0

      arm_rot_1:   {p: 5000.0, i: 0.01, d: 100.0}
      arm_rot_2:   {p: 5000.0, i: 0.01, d: 100.0}
      arm_rot_3:   {p: 5000.0, i: 0.01, d: 100.0}
      arm_rot_4:   {p: 5000.0, i: 0.01, d: 100.0}
      arm_rot_5:   {p: 5000.0, i: 0.01, d: 100.0}
      arm_rot_6:   {p: 5000.0, i: 0.01, d: 100.0}
      finger_pri_1:  {p: 5000.0, i: 0.01, d: 100.0}
      finger_pri_2:  {p: 5000.0, i: 0.01, d: 100.0}

