zrobo:

  # Arm controller configuration.
  group_arm_controller:
    type: "position_controllers/JointTrajectoryController"
    joints:
      - arm_rot_1
      - arm_rot_2
      - arm_rot_3
      - arm_rot_4
      - arm_rot_5
      - arm_rot_6
    #gains:
      #arm_rot_1:   {p: 5000.0, i: 0.0, d: 10}
      #arm_rot_2:   {p: 5000.0, i: 0.0, d: 10}
      #arm_rot_3:   {p: 5000.0, i: 0.0, d: 10}
      #arm_rot_4:   {p: 5000.0, i: 0.0, d: 10}
      #arm_rot_5:   {p: 5000.0, i: 0.0, d: 10}
      #arm_rot_6:   {p: 5000.0, i: 0.0, d: 10}

  group_gripper_controller:
    type: "position_controllers/JointTrajectoryController"
    joints:
      - finger_pri_1
      - finger_pri_2
    #gains:
      #finger_pri_1:  {p: 5000.0, i: 0.0, d: 10}
      #finger_pri_2:  {p: 5000.0, i: 0.0, d: 10}



  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 100
  
   # Position Controllers ---------------------------------------
  joint1_position_controller:
    type: effort_controllers/JointPositionController
    joint: FL_hip_joint
    pid: {p: 5000.0, i: 0.01, d: 100.0}
  joint2_position_controller:
    type: effort_controllers/JointPositionController
    joint: FL_thigh_joint
    pid: {p: 5000.0, i: 0.01, d: 100.0}
  joint3_position_controller:
    type: effort_controllers/JointPositionController
    joint: FL_calf_joint
    pid: {p: 5000.0, i: 0.01, d: 100.0}
  joint4_position_controller:
    type: effort_controllers/JointPositionController
    joint: FR_hip_joint
    pid: {p: 5000.0, i: 0.01, d: 100.0}
  joint5_position_controller:
    type: effort_controllers/JointPositionController
    joint: FR_thigh_joint
    pid: {p: 5000.0, i: 0.01, d: 100.0}
  joint6_position_controller:
    type: effort_controllers/JointPositionController
    joint: FR_calf_joint
    pid: {p: 5000.0, i: 0.01, d: 100.0}
  joint7_position_controller:
    type: effort_controllers/JointPositionController
    joint: BL_hip_joint
    pid: {p: 5000.0, i: 0.01, d: 100.0}
  joint8_position_controller:
    type: effort_controllers/JointPositionController
    joint: BL_thigh_joint
    pid: {p: 5000.0, i: 0.01, d: 100.0}
  joint9_position_controller:
    type: effort_controllers/JointPositionController
    joint: BL_calf_joint
    pid: {p: 5000.0, i: 0.01, d: 100.0}
  joint10_position_controller:
    type: effort_controllers/JointPositionController
    joint: BR_hip_joint
    pid: {p: 5000.0, i: 0.01, d: 100.0}
  joint11_position_controller:
    type: effort_controllers/JointPositionController
    joint: BR_thigh_joint
    pid: {p: 5000.0, i: 0.01, d: 100.0}
  joint12_position_controller:
    type: effort_controllers/JointPositionController
    joint: BR_calf_joint
    pid: {p: 5000.0, i: 0.01, d: 100.0}
  joint13_position_controller:
    type: effort_controllers/JointPositionController
    joint: FL_wheel_joint
    pid: {p: 5000.0, i: 0.01, d: 100.0}

  joint14_position_controller:
    type: effort_controllers/JointPositionController
    joint: FR_wheel_joint
    pid: {p: 5000.0, i: 0.01, d: 100.0}

  joint15_position_controller:
    type: effort_controllers/JointPositionController
    joint: BL_wheel_joint
    pid: {p: 5000.0, i: 0.01, d: 100.0}
  joint16_position_controller:
    type: effort_controllers/JointPositionController
    joint: BR_wheel_joint
    pid: {p: 5000.0, i: 0.01, d: 100.0}

  joint17_position_controller:
    type: effort_controllers/JointPositionController
    joint: arm_rot_1
    pid: {p: 5000.0, i: 0.01, d: 100.0}

  joint18_position_controller:
    type: effort_controllers/JointPositionController
    joint: arm_rot_2
    pid: {p: 5000.0, i: 0.01, d: 100.0}

  joint19_position_controller:
    type: effort_controllers/JointPositionController
    joint: arm_rot_3
    pid: {p: 5000.0, i: 0.01, d: 100.0}

  joint20_position_controller:
    type: effort_controllers/JointPositionController
    joint: arm_rot_4
    pid: {p: 5000.0, i: 0.01, d: 100.0}

  joint21_position_controller:
    type: effort_controllers/JointPositionController
    joint: arm_rot_5
    pid: {p: 5000.0, i: 0.01, d: 100.0}

  joint22_position_controller:
    type: effort_controllers/JointPositionController
    joint: arm_rot_6
    pid: {p: 5000.0, i: 0.01, d: 100.0}

  joint23_position_controller:
    type: effort_controllers/JointPositionController
    joint: finger_pri_1
    pid: {p: 5000.0, i: 0.01, d: 100.0}

  joint24_position_controller:
    type: effort_controllers/JointPositionController
    joint: finger_pri_2
    pid: {p: 5000.0, i: 0.01, d: 100.0}

zrobo/gazebo_ros_control/pid_gains:
      arm_rot_1:   {p: 5000.0, i: 0.01, d: 100.0}
      arm_rot_2:   {p: 5000.0, i: 0.01, d: 100.0}
      arm_rot_3:   {p: 5000.0, i: 0.01, d: 100.0}
      arm_rot_4:   {p: 5000.0, i: 0.01, d: 100.0}
      arm_rot_5:   {p: 5000.0, i: 0.01, d: 100.0}
      arm_rot_6:   {p: 5000.0, i: 0.01, d: 100.0}
      finger_pri_1:  {p: 5000.0, i: 0.01, d: 100.0}
      finger_pri_2:  {p: 5000.0, i: 0.01, d: 100.0}


